# Generated by Django 5.2.1 on 2025-05-14 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endusers',
            name='assigned_caddie',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.listofcaddies'),
        ),
        migrations.DeleteModel(
            name='TeeTime',
        ),
    ]
