# Generated by Django 5.2.1 on 2025-05-16 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_caddie_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('caddie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.caddie')),
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.field')),
            ],
        ),
    ]
