# Generated by Django 5.2.1 on 2025-05-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day1_score', models.IntegerField(blank=True, null=True)),
                ('day2_score', models.IntegerField(blank=True, null=True)),
                ('day3_score', models.IntegerField(blank=True, null=True)),
                ('day4_score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
