# Generated by Django 5.2.1 on 2025-05-12 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_endusers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teetimes',
            old_name='teeTime',
            new_name='tee_time',
        ),
        migrations.AddField(
            model_name='teetimes',
            name='caddie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tee_times', to='core.listofcaddies'),
        ),
        migrations.AddField(
            model_name='teetimes',
            name='user',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='tee_times', to='core.endusers'),
            preserve_default=False,
        ),
    ]
