# Generated by Django 5.2.1 on 2025-05-22 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.schedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.endusers')),
            ],
        ),
    ]
